version: '3.8'

services:
  nessie:
    image: projectnessie/nessie:latest
    container_name: nessie
    ports:
      - "19120:19120"
    environment:
      QUARKUS_PROFILE: in-memory

  trino:
    image: trinodb/trino:latest
    container_name: trino
    ports:
      - "8080:8080"
    volumes:
      - ./trino/etc:/etc/trino
      - ./warehouse:/opt/warehouse  # локальное хранилище Iceberg-таблиц
    depends_on:
      - nessie
