version: '3.8'

services:
  nessie:
    image: projectnessie/nessie:latest
    container_name: nessie
    ports:
      - "19120:19120"
    environment:
      AWS_REGION: us-east-1
      QUARKUS_PROFILE: in-memory
    networks:
      - my-network
    depends_on:
      - minio

  trino:
    image: trinodb/trino:latest
    container_name: trino
    ports:
      - "8080:8080"
    environment:
      AWS_REGION: us-east-1
    volumes:
      - ./trino/etc:/etc/trino
      - ./warehouse:/opt/warehouse  # локальное хранилище Iceberg-таблиц
    networks:
      - my-network
    depends_on:
      - nessie
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    networks:
      - my-network
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  minio-data:
networks:
  my-network:
    driver: bridge